#!/usr/bin/with-contenv bash

# create directory structure
mkdir -p \
	/config/data/{plugins,viewcache}

# check for config file and copy default if needed
[[ ! -f "/config/data/config.php" ]] && \
	cp /app/grocy/config-dist.php /config/data/config.php

# check for plugins existence, copy if required
[[ ! -f "/config/data/plugins/DemoBarcodeLookupPlugin.php" ]] && \
	cp -R /defaults/plugins/ /config/data

# create symlinks
symlinks=( \
/app/grocy/data/plugins \
/app/grocy/data/viewcache \
/app/grocy/data 
)

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && rm -rf "$i"
[[ ! -L "$i" ]] && ln -s /config/"$(basename "$i")" "$i"
done

chown -R abc:abc \
	/app/grocy \
	/config
