#!/usr/bin/with-contenv bash

# create directory structure
mkdir -p \
    /config/data/{plugins,viewcache}

# check for config file and copy default if needed
[[ ! -f "/config/data/config.php" ]] && \
    cp /app/grocy/config-dist.php /config/data/config.php

[[ ! -f "/config/data/plugins/DemoBarcodeLookupPlugin.php" ]] && \
    cp -R /defaults/plugins /config/data

# create symlinks
i=/app/grocy/data
[[ -e "$i" && ! -L "$i" ]] && \
rm -rf "$i" && \
ln -s /config/"$(basename "$i")" "$i"

chown -R abc:abc \
    /app/grocy \
    /config
